### ISSUE TITLE
Development schedule

### ISSUE THREAD

**Issue by ksterne** [vtsuperdarn/VTRST3.5#26]
Even though there isn't a lot of active development going on with this repository, would there be any opposition of mirroring the branch merging schedule of davitpy?  It's been quite a while since develop was merged into master.  And though the develop branch is set to be the default, it may be good to keep master up-to-date as new users/devs will assume master is the best version.

**Comment by egthomas** [comment]
We've shifted active development to a non-institution-specific repository for the RST here:

https://github.com/SuperDARN/rst

However that is a valid point of bringing the master branch up to date with develop and is on the to-do list.

**Comment by sshepherd** [comment]
IGRF, AACGM-v2, MLT and gridding development are happening on the repository that Evan has included above. Hopefully we can make some progress on new version of RST before the workshop.

**Comment by ksterne** [comment]
Any plans or ideas on how we'll transition from this repo to the new one?  There are several people who are using this repo as source code.

**Comment by egthomas** [comment]
There haven't been any commits to any branches (besides debugging on the bugfix-usask_freq_chan branch over the last few days) since we created the new repository in November 2016.  It should just be a matter of downloading from the new repository and compiling - which will actually be easier, since I've streamlined things and fixed it so that compilation doesn't fail like on VTRST3.5.
